# Generated by Django 4.2.6 on 2023-10-21 01:03

import apps.digitalization.storage_backends
import apps.digitalization.validators
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VouchersView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file', models.CharField(blank=True, max_length=300, null=True)),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('voucher_state', models.CharField(blank=True, max_length=300, null=True)),
                ('collection_code', models.CharField(blank=True, max_length=300, null=True)),
                ('other_catalog_numbers', models.CharField(blank=True, max_length=13, null=True)),
                ('catalog_number', models.IntegerField(blank=True, null=True)),
                ('recorded_by', models.CharField(blank=True, max_length=300, null=True)),
                ('record_number', models.CharField(blank=True, max_length=13, null=True)),
                ('organism_remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=300, null=True)),
                ('locality', models.CharField(blank=True, max_length=300, null=True)),
                ('verbatim_elevation', models.IntegerField(blank=True, null=True)),
                ('georeferenced_date', models.DateTimeField(blank=True, null=True)),
                ('decimal_latitude', models.FloatField(blank=True, null=True)),
                ('decimal_longitude', models.FloatField(blank=True, null=True)),
                ('identified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('identified_date', models.CharField(blank=True, max_length=100, null=True)),
                ('decimal_latitude_public', models.FloatField(blank=True, null=True)),
                ('decimal_longitude_public', models.FloatField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, default=3, null=True)),
            ],
            options={
                'db_table': 'vouchers_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BiodataCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('catalog_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('qr_generated', models.BooleanField(default=False)),
                ('voucher_state', models.IntegerField(choices=[(0, 'Sin Estado'), (1, 'Encontrado'), (2, 'No Encontrado'), (3, 'En Préstamo'), (4, 'Extraviado'), (5, 'En Préstado Encontrado'), (6, 'En curatoria'), (7, 'Digitalizado'), (8, 'Pendiente')], default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'BIODATA Codes',
            },
        ),
        migrations.CreateModel(
            name='ColorProfileFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/color_profile/', validators=[apps.digitalization.validators.validate_file_size])),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Herbarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('collection_code', models.CharField(max_length=6)),
                ('institution_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Herbariums',
            },
        ),
        migrations.CreateModel(
            name='PriorityVouchersFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/priority_vouchers/', validators=[apps.digitalization.validators.validate_file_size])),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('herbarium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalization.herbarium')),
            ],
            options={
                'verbose_name_plural': 'Priority Vouchers Files',
            },
        ),
        migrations.CreateModel(
            name='VoucherImported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_catalog_numbers', models.CharField(blank=True, max_length=13, null=True)),
                ('catalog_number', models.IntegerField(blank=True, null=True)),
                ('recorded_by', models.CharField(blank=True, max_length=300, null=True)),
                ('record_number', models.CharField(blank=True, max_length=13, null=True)),
                ('organism_remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('locality', models.CharField(blank=True, max_length=300, null=True)),
                ('verbatim_elevation', models.IntegerField(blank=True, null=True)),
                ('georeferenced_date', models.DateTimeField(blank=True, null=True)),
                ('decimal_latitude', models.FloatField(blank=True, null=True)),
                ('decimal_longitude', models.FloatField(blank=True, null=True)),
                ('identified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('identified_date', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('image_resized_10', models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('image_resized_60', models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('image_public', models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.PublicMediaStorage(), upload_to='')),
                ('image_public_resized_10', models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.PublicMediaStorage(), upload_to='')),
                ('image_public_resized_60', models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.PublicMediaStorage(), upload_to='')),
                ('image_raw', models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('decimal_latitude_public', models.FloatField(blank=True, null=True)),
                ('decimal_longitude_public', models.FloatField(blank=True, null=True)),
                ('point_public', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('priority', models.IntegerField(blank=True, default=3, null=True)),
                ('biodata_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalization.biodatacode')),
                ('herbarium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalization.herbarium')),
                ('scientific_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.species')),
                ('vouchers_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalization.priorityvouchersfile')),
            ],
            options={
                'verbose_name_plural': 'Vouchers',
            },
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('short_name', models.CharField(max_length=20, null=True)),
                ('added_by', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HerbariumMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herbarium', models.ManyToManyField(to='digitalization.herbarium')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('terminated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('color_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digitalization.colorprofilefile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('herbarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalization.herbarium')),
            ],
            options={
                'verbose_name_plural': 'Generated Pages',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=apps.digitalization.storage_backends.PublicMediaStorage(), upload_to='gallery')),
                ('taken_by', models.CharField(blank=True, max_length=300, null=True)),
                ('upload_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('licence', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digitalization.licence')),
                ('scientific_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.species')),
                ('specimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digitalization.biodatacode')),
                ('upload_by', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='biodatacode',
            name='herbarium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalization.herbarium'),
        ),
        migrations.AddField(
            model_name='biodatacode',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalization.generatedpage'),
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(storage=apps.digitalization.storage_backends.PublicMediaStorage(), upload_to='banners')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalization.voucherimported')),
                ('specie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.species')),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('temporal', models.BooleanField(default=False)),
                ('protected_area', models.BooleanField(default=False)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(dim=3, srid=4326)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW vouchers_view AS
            SELECT voucher.id,
                   voucherfile.file,
                   biodatacode.code,
                   biodatacode.voucher_state,
                   herbarium.collection_code,
                   voucher.other_catalog_numbers,
                   voucher.catalog_number,
                   voucher.recorded_by,
                   voucher.record_number,
                   voucher.organism_remarks,
                   species.scientific_name,
                   voucher.locality,
                   voucher.verbatim_elevation,
                   voucher.georeferenced_date,
                   voucher.decimal_latitude,
                   voucher.decimal_longitude,
                   voucher.identified_by,
                   voucher.identified_date,
                   voucher.decimal_latitude_public,
                   voucher.decimal_longitude_public,
                   voucher.priority
            FROM digitalization_voucherimported voucher
                 JOIN digitalization_herbarium herbarium ON voucher.herbarium_id = herbarium.id
                 JOIN digitalization_priorityvouchersfile voucherfile ON voucher.vouchers_file_id = voucherfile.id
                 JOIN digitalization_biodatacode biodatacode ON voucher.biodata_code_id = biodatacode.id
                 JOIN catalog_species species ON voucher.scientific_name_id = species.id;
            """
        ),
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX vouchers_view_id_idx
                ON vouchers_view (id);
            """
        ),
    ]
