# Generated by Django 4.2.6 on 2023-11-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='areas',
            name='name_es',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='generatedpage',
            name='name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='generatedpage',
            name='name_es',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='herbarium',
            name='name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='herbarium',
            name='name_es',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='licence',
            name='name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='licence',
            name='name_es',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='biodatacode',
            name='voucher_state',
            field=models.IntegerField(choices=[(0, 'No State'), (1, 'Found'), (2, 'Not Found'), (3, 'Borrowed'), (4, 'Lost'), (5, 'Found And Borrowed'), (6, 'In Curatorship'), (7, 'Digitalized'), (8, 'Pending')], default=0),
        ),
    ]
