# Generated by Django 4.1.7 on 2023-03-25 06:16

import apps.digitalization.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
        ('digitalization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=apps.digitalization.storage_backends.PrivateMediaStorage(), upload_to='gallery')),
                ('taken_by', models.CharField(blank=True, max_length=300, null=True)),
                ('upload_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('licence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digitalization.licence')),
                ('scientificName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.species')),
                ('specimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digitalization.biodatacode')),
                ('upload_by', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
