# Generated by Django 4.2.4 on 2023-09-01 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodatacode',
            old_name='catalogNumber',
            new_name='catalog_number',
        ),
        migrations.RenameField(
            model_name='galleryimage',
            old_name='scientificName',
            new_name='scientific_name',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='occurrenceID',
            new_name='biodata_code',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='catalogNumber',
            new_name='catalog_number',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='decimalLatitude',
            new_name='decimal_latitude',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='decimalLatitude_public',
            new_name='decimal_latitude_public',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='decimalLongitude',
            new_name='decimal_longitude',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='decimalLongitude_public',
            new_name='decimal_longitude_public',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='georeferencedDate',
            new_name='georeference_date',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='identifiedBy',
            new_name='identified_by',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='dateIdentified',
            new_name='identified_date',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='organismRemarks',
            new_name='organism_remarks',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='otherCatalogNumbers',
            new_name='other_catalog_numbers',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='recordNumber',
            new_name='record_number',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='recordedBy',
            new_name='recorded_by',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='scientificName',
            new_name='scientific_name',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='verbatimElevation',
            new_name='verbatim_elevation',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='licence',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digitalization.licence'),
        ),
    ]
