# Generated by Django 4.2.6 on 2023-12-13 13:08

import apps.digitalization.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0002_areas_name_en_areas_name_es_generatedpage_name_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedpage',
            old_name='terminated',
            new_name='finished',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='thumbnail',
            field=models.ImageField(null=True, storage=apps.digitalization.storage_backends.PublicMediaStorage(), upload_to='gallery'),
        ),
    ]
