# Generated by Django 4.2.4 on 2023-09-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0002_rename_catalognumber_biodatacode_catalog_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucherimported',
            old_name='georeference_date',
            new_name='georeferenced_date',
        ),
        migrations.AlterField(
            model_name='biodatacode',
            name='voucher_state',
            field=models.IntegerField(choices=[(0, 'Sin Estado'), (1, 'Encontrado'), (2, 'No Encontrado'), (3, 'En Préstamo'), (4, 'Extraviado'), (5, 'En Préstado Encontrado'), (6, 'En curatoria'), (7, 'Digitalizado'), (8, 'Pendiente')], default=0),
        ),
    ]
