# Generated by Django 4.2.6 on 2023-12-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0003_rename_terminated_generatedpage_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='aspect_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
