# Generated by Django 4.1.7 on 2023-04-12 11:59

import apps.digitalization.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('digitalization', '0003_alter_galleryimage_licence'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(storage=apps.digitalization.storage_backends.PublicMediaStorage(), upload_to='banners')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalization.voucherimported')),
                ('specie_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.species')),
            ],
        ),
    ]
