# Generated by Django 4.2.5 on 2023-10-17 21:31

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digitalization', '0003_rename_georeference_date_voucherimported_georeferenced_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerimage',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='generatedpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('temporal', models.BooleanField(default=False)),
                ('protected_area', models.BooleanField(default=False)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(dim=3, srid=4326)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
