# Generated by Django 4.2.6 on 2023-12-28 14:17

import apps.digitalization.storage_backends
import apps.digitalization.validators
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_classname_options_alter_commonname_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digitalization', '0004_galleryimage_aspect_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='Name')),
                ('name_es', models.CharField(max_length=300, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=300, null=True, verbose_name='Name')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Geometry')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.AlterModelOptions(
            name='biodatacode',
            options={'verbose_name': 'BIODATA Code', 'verbose_name_plural': 'BIODATA Codes'},
        ),
        migrations.AlterModelOptions(
            name='colorprofilefile',
            options={'verbose_name': 'Color Profile File', 'verbose_name_plural': 'Color Profile Files'},
        ),
        migrations.AlterModelOptions(
            name='generatedpage',
            options={'verbose_name': 'Generated Page', 'verbose_name_plural': 'Generated Pages'},
        ),
        migrations.AlterModelOptions(
            name='herbarium',
            options={'verbose_name': 'Herbarium', 'verbose_name_plural': 'Herbariums'},
        ),
        migrations.AlterModelOptions(
            name='herbariummember',
            options={'verbose_name': 'Herbarium', 'verbose_name_plural': 'Herbariums'},
        ),
        migrations.AlterModelOptions(
            name='priorityvouchersfile',
            options={'verbose_name': 'Priority Vouchers File', 'verbose_name_plural': 'Priority Vouchers Files'},
        ),
        migrations.AlterModelOptions(
            name='voucherimported',
            options={'verbose_name': 'Voucher', 'verbose_name_plural': 'Vouchers'},
        ),
        migrations.RemoveField(
            model_name='bannerimage',
            name='specie',
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='species',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.species', verbose_name='Species'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='banner',
            field=models.ImageField(storage=apps.digitalization.storage_backends.PublicMediaStorage(), upload_to='banners', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalization.voucherimported', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='biodatacode',
            name='catalog_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Catalog Number'),
        ),
        migrations.AlterField(
            model_name='biodatacode',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='biodatacode',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='biodatacode',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='biodatacode',
            name='herbarium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalization.herbarium', verbose_name='Herbarium'),
        ),
        migrations.AlterField(
            model_name='biodatacode',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalization.generatedpage', verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='biodatacode',
            name='qr_generated',
            field=models.BooleanField(default=False, verbose_name='Generated QR?'),
        ),
        migrations.AlterField(
            model_name='biodatacode',
            name='voucher_state',
            field=models.IntegerField(choices=[(0, 'No State'), (1, 'Found'), (2, 'Not Found'), (3, 'Borrowed'), (4, 'Lost'), (5, 'Found And Borrowed'), (6, 'In Curatorship'), (7, 'Digitalized'), (8, 'Pending')], default=0, verbose_name='Voucher State'),
        ),
        migrations.AlterField(
            model_name='colorprofilefile',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='colorprofilefile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='colorprofilefile',
            name='file',
            field=models.FileField(upload_to='uploads/color_profile/', validators=[apps.digitalization.validators.validate_file_size], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='aspect_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='Aspect Ratio'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(storage=apps.digitalization.storage_backends.PublicMediaStorage(), upload_to='gallery', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='licence',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digitalization.licence', verbose_name='Licence'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='scientific_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.species', verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='specimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digitalization.biodatacode', verbose_name='Specimen'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='taken_by',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Taken by'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='thumbnail',
            field=models.ImageField(null=True, storage=apps.digitalization.storage_backends.PublicMediaStorage(), upload_to='gallery', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Upload at'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='upload_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Upload by'),
        ),
        migrations.AlterField(
            model_name='generatedpage',
            name='color_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digitalization.colorprofilefile', verbose_name='Color Profile File'),
        ),
        migrations.AlterField(
            model_name='generatedpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='generatedpage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='generatedpage',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Finished?'),
        ),
        migrations.AlterField(
            model_name='generatedpage',
            name='herbarium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalization.herbarium', verbose_name='Herbarium'),
        ),
        migrations.AlterField(
            model_name='generatedpage',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='generatedpage',
            name='name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='generatedpage',
            name='name_es',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='herbarium',
            name='collection_code',
            field=models.CharField(help_text='No más de 6 letras', max_length=6, verbose_name='Collection Code'),
        ),
        migrations.AlterField(
            model_name='herbarium',
            name='institution_code',
            field=models.CharField(blank=True, help_text='No más de 10 letras', max_length=10, null=True, verbose_name='Institution Code'),
        ),
        migrations.AlterField(
            model_name='herbarium',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='herbarium',
            name='name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='herbarium',
            name='name_es',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='herbariummember',
            name='herbarium',
            field=models.ManyToManyField(to='digitalization.herbarium', verbose_name='Herbarium'),
        ),
        migrations.AlterField(
            model_name='herbariummember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='added_by',
            field=models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='name',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='name_es',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='short_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='priorityvouchersfile',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='priorityvouchersfile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='priorityvouchersfile',
            name='file',
            field=models.FileField(upload_to='uploads/priority_vouchers/', validators=[apps.digitalization.validators.validate_file_size], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='priorityvouchersfile',
            name='herbarium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalization.herbarium', verbose_name='Herbarium'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='biodata_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalization.biodatacode', verbose_name='BIODATA Code'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='catalog_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Catalog Number'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='decimal_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='decimal_latitude_public',
            field=models.FloatField(blank=True, null=True, verbose_name='Public Latitude'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='decimal_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='decimal_longitude_public',
            field=models.FloatField(blank=True, null=True, verbose_name='Public Longitude'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='georeferenced_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Georeferenced Date'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='herbarium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalization.herbarium', verbose_name='Herbarium'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='identified_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Identified by'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='identified_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Identified Date'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='image_public',
            field=models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.PublicMediaStorage(), upload_to='', verbose_name='Public Image'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='image_public_resized_10',
            field=models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.PublicMediaStorage(), upload_to='', verbose_name='Escala de imagen pública 10 veces más pequeña'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='image_public_resized_60',
            field=models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.PublicMediaStorage(), upload_to='', verbose_name='Escala de imagen pública 60 veces más pequeña'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='image_raw',
            field=models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='Raw Image'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='image_resized_10',
            field=models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='Escala de imagen 10 veces más pequeña'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='image_resized_60',
            field=models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='Escala de imagen 60 veces más pequeña'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='locality',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Locality'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='organism_remarks',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='other_catalog_numbers',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Other Catalog Numbers'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='point_public',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Public Point'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='priority',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='record_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Record Number'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='recorded_by',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Recorded by'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='scientific_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.species', verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='verbatim_elevation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Altitude'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='vouchers_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalization.priorityvouchersfile', verbose_name='Priority Vouchers File'),
        ),
        migrations.CreateModel(
            name='ProtectedArea',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='digitalization.area')),
                ('mma_code', models.CharField(max_length=100, null=True, verbose_name='MMA Code')),
                ('designation_type', models.IntegerField(choices=[(0, 'Protected Area'), (1, 'Private Conservation'), (2, 'Other Designations')], default=0, verbose_name='Designation Type')),
                ('category', models.CharField(max_length=100, null=True, verbose_name='Category')),
                ('category_es', models.CharField(max_length=100, null=True, verbose_name='Category')),
                ('category_en', models.CharField(max_length=100, null=True, verbose_name='Category')),
                ('iucn_management_category', models.CharField(choices=[('Ia', 'strict nature reserve'), ('Ib', 'wilderness area'), ('II', 'national park'), ('III', 'natural monument or feature'), ('IV', 'habitat or species management area'), ('V', 'protected landscape or seascape'), ('VI', 'protected area with sustainable use of natural resources')], max_length=5, null=True, verbose_name='IUCN Management Category')),
            ],
            options={
                'verbose_name': 'Protected Area',
                'verbose_name_plural': 'Protected Areas',
            },
            bases=('digitalization.area',),
        ),
        migrations.CreateModel(
            name='TemporalArea',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='digitalization.area')),
                ('access', models.IntegerField(default=0, verbose_name='Access')),
            ],
            options={
                'verbose_name': 'Temporal Area',
                'verbose_name_plural': 'Temporal Areas',
            },
            bases=('digitalization.area',),
        ),
        migrations.DeleteModel(
            name='Areas',
        ),
    ]
