# Generated by Django 4.2.6 on 2024-06-04 15:08

import apps.digitalization.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digitalization', '0005_area_alter_biodatacode_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostprocessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('file', models.FileField(storage=apps.digitalization.storage_backends.PrivateMediaStorage(), upload_to='logs/', verbose_name='File')),
                ('found_images', models.IntegerField(default=0, verbose_name='Found Images')),
                ('processed_images', models.IntegerField(default=0, verbose_name='Processed Images')),
                ('failed_images', models.IntegerField(default=0, verbose_name='Failed Images')),
                ('scheduled', models.BooleanField(verbose_name='Scheduled')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Postprocessing Log',
                'verbose_name_plural': 'Postprocessing Logs',
            },
        ),
    ]
