# Generated by Django 4.1.7 on 2023-04-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0005_alter_galleryimage_image_alter_licence_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='short_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
