# Generated by Django 4.2.6 on 2024-06-28 14:55

import apps.digitalization.storage_backends
import apps.digitalization.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0006_postprocessinglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorprofilefile',
            name='file',
            field=models.FileField(storage=apps.digitalization.storage_backends.PrivateMediaStorage(), upload_to='uploads/color_profile/', validators=[apps.digitalization.validators.validate_file_size], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='priorityvouchersfile',
            name='file',
            field=models.FileField(storage=apps.digitalization.storage_backends.PrivateMediaStorage(), upload_to='uploads/priority_vouchers/', validators=[apps.digitalization.validators.validate_file_size], verbose_name='File'),
        ),
    ]
