# Generated by Django 4.2.6 on 2024-08-21 13:11
import boto3
from django.db import migrations, models
from tqdm import tqdm

import apps.digitalization.storage_backends
from apps.digitalization.models import VoucherImported
from apps.digitalization.storage_backends import PrivateMediaStorage

s3_client = boto3.client('s3')


def change_storage_class(apps, schema_editor):
    error_file = open("errors.txt", "w")
    for obj in tqdm(VoucherImported.objects.all(), desc="Changing classes", unit="voucher"):
        for attr_img, new_class in [
            ("image_raw", "DEEP_ARCHIVE"),
            ("image", "STANDARD_IA"),
            ("image_resized_10", "STANDARD_IA"),
            ("image_resized_60", "STANDARD_IA"),
        ]:
            if getattr(obj, attr_img):
                key_object = f"{PrivateMediaStorage().location}/{getattr(obj, attr_img).name}"
                try:
                    s3_client.copy_object(
                        Bucket=getattr(obj, attr_img).storage.bucket_name,
                        Key=key_object,
                        CopySource={
                            'Bucket': getattr(obj, attr_img).storage.bucket_name,
                            'Key': key_object
                        },
                        StorageClass=new_class,
                    )
                except Exception as e:
                    error_file.write(f"{key_object}: {e}\n")
                    pass
    error_file.close()
    return


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0007_alter_colorprofilefile_file_and_more'),
    ]

    operations = [
        migrations.RunPython(change_storage_class),
        migrations.AlterField(
            model_name='voucherimported',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.IAPrivateMediaStorage(), upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='image_raw',
            field=models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.GlacierPrivateMediaStorage(), upload_to='', verbose_name='Raw Image'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='image_resized_10',
            field=models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.IAPrivateMediaStorage(), upload_to='', verbose_name='Escala de imagen 10 veces más pequeña'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='image_resized_60',
            field=models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.IAPrivateMediaStorage(), upload_to='', verbose_name='Escala de imagen 60 veces más pequeña'),
        ),
    ]
