# Generated by Django 4.2.6 on 2024-09-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0008_alter_voucherimported_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherimported',
            name='record_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Record Number'),
        ),
    ]
