# Generated by Django 4.2.6 on 2025-01-31 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('digitalization', '0009_alter_voucherimported_record_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Holotype'), (2, 'Lectotype'), (3, 'Isotype'), (4, 'Syntype'), (5, 'Paratype'), (6, 'Neotype'), (7, 'Epitype')], verbose_name='Type')),
                ('taxon_id', models.PositiveIntegerField()),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalization.voucherimported', verbose_name='Specimen')),
                ('taxon_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
