# Generated by Django 5.1.6 on 2025-04-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0010_typestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herbarium',
            name='collection_code',
            field=models.CharField(help_text='No más de 6 letras', max_length=6, unique=True, verbose_name='Collection Code'),
        ),
    ]
