# Generated by Django 5.1.6 on 2025-04-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('digitalization', '0011_alter_herbarium_collection_code'),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE digitalization_voucherimported
            SET identified_date = (identified_date)::FLOAT::BIGINT::TEXT
            WHERE identified_date != 'nan';
            """
        ),
        migrations.RunSQL(
            """
            UPDATE digitalization_voucherimported
            SET identified_date = NULL
            WHERE identified_date = 'nan' OR identified_date = '0';
            """
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='identified_date',
            new_name='date_identified',
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='date_identified',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Date Identified'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='georeferenced_date',
            field=models.DateField(blank=True, null=True, verbose_name='Georeferenced Date'),
        ),
    ]
