# Generated by Django 5.1.6 on 2025-04-11 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0012_remove_voucherimported_identified_date_and_more'),
        ('metadata', '0004_licence_alter_emldataset_licensed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='licence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.licence', verbose_name='Licence'),
        ),
        migrations.DeleteModel(
            name='Licence',
        ),
    ]
