# Generated by Django 5.1.6 on 2025-04-11 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0013_alter_galleryimage_licence_delete_licence'),
        ('metadata', '0004_licence_alter_emldataset_licensed'),
    ]

    operations = [
        migrations.AddField(
            model_name='herbarium',
            name='metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metadata.eml', verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='licence',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.licence', verbose_name='Licence'),
        ),
    ]
