# Generated by Django 5.1.6 on 2025-08-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0014_herbarium_metadata_alter_galleryimage_licence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typestatus',
            name='type',
            field=models.IntegerField(choices=[(0, 'Type'), (1, 'Holotype'), (2, 'Lectotype'), (3, 'Isotype'), (4, 'Syntype'), (5, 'Paratype'), (6, 'Neotype'), (7, 'Epitype')], verbose_name='Type'),
        ),
    ]
