# Generated by Django 5.1.6 on 2025-08-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0015_alter_typestatus_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herbarium',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='herbarium',
            name='name_es',
        ),
    ]
