# Generated by Django 5.1.6 on 2026-04-14 20:12

import apps.digitalization.storage_backends
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0016_remove_herbarium_name_en_remove_herbarium_name_es'),
        ('metadata', '0004_licence_alter_emldataset_licensed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='licence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.licence', verbose_name='Licence'),
        ),
        migrations.AlterField(
            model_name='typestatus',
            name='type',
            field=models.IntegerField(choices=[(0, 'Type'), (1, 'Holotype'), (2, 'Lectotype'), (3, 'Isotype'), (4, 'Syntype'), (5, 'Paratype'), (6, 'Neotype'), (7, 'Epitype'), (8, 'Isolectotype'), (9, 'Isoneotype'), (10, 'Topotype'), (11, 'Iconotype'), (12, 'Clastotype'), (13, 'Cotype'), (14, 'Archeotype'), (15, 'Isosyntype')], verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='voucherimported',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.GlacierPrivateMediaStorage(), upload_to='', verbose_name='Image'),
        ),
    ]
