# Generated by Django 5.1.6 on 2026-06-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20250813_1626'),
        ('digitalization', '0017_alter_galleryimage_licence_alter_typestatus_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoucherImported',
            new_name='Voucher',
        ),
    ]
