# Generated by Django 5.1.6 on 2026-04-18 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0017_alter_galleryimage_licence_alter_typestatus_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherimported',
            name='code',
            field=models.CharField(default='1', max_length=30, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucherimported',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='voucherimported',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucherimported',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalization.generatedpage', verbose_name='Page'),
        ),
        migrations.AddField(
            model_name='voucherimported',
            name='qr_generated',
            field=models.BooleanField(default=False, verbose_name='Generated QR?'),
        ),
        migrations.AddField(
            model_name='voucherimported',
            name='voucher_state',
            field=models.IntegerField(choices=[(0, 'No State'), (1, 'Found'), (2, 'Not Found'), (3, 'Borrowed'), (4, 'Lost'), (5, 'Found And Borrowed'), (6, 'In Curatorship'), (7, 'Digitalized'), (8, 'Pending')], default=0, verbose_name='Voucher State'),
        ),
    ]
