# Generated by Django 5.1.6 on 2026-04-18 00:11

from django.db import migrations
from tqdm import tqdm


def migrate_biodata_code(apps, schema_editor) -> None:
    voucher_imported = apps.get_model("digitalization", "VoucherImported")
    for voucher in tqdm(voucher_imported.objects.all()):
        obj = voucher.biodata_code
        voucher.code = obj.code
        voucher.created_at = obj.created_at
        voucher.created_by = obj.created_by
        voucher.qr_generated = obj.qr_generated
        voucher.page = obj.page
        voucher.voucher_state = obj.voucher_state
        voucher.save()


def unmigrate_biodata_code(apps, schema_editor) -> None:
    voucher_imported = apps.get_model("digitalization", "VoucherImported")
    for voucher in tqdm(voucher_imported.objects.all()):
        obj = voucher.biodata_code
        obj.code = voucher.code
        obj.created_at = voucher.created_at
        obj.created_by = voucher.created_by
        obj.qr_generated = voucher.qr_generated
        obj.page = voucher.page
        obj.voucher_state = voucher.voucher_state
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0018_voucherimported_code_voucherimported_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_biodata_code, unmigrate_biodata_code),
    ]
