# Generated by Django 5.1.6 on 2026-06-10 17:11
from tqdm import tqdm

import apps.digitalization.storage_backends
import django.db.models.deletion
from django.db import migrations, models

def migrate_voucherimported(apps, schema_editor):
    voucher = apps.get_model('digitalization', 'voucher')
    voucher_imported = apps.get_model('digitalization', 'voucherimported')
    for obj in tqdm(voucher.objects.all()):
        obj.__class__ = voucher_imported
        obj.save()
        obj.new_vouchers_file = obj.vouchers_file
        obj.new_biodata_code = obj.biodata_code
        obj.new_image = obj.image
        obj.new_image_resized_10 = obj.image_resized_10
        obj.new_image_resized_60 = obj.image_resized_60
        obj.new_image_public = obj.image_public
        obj.new_image_public_resized_60 = obj.image_public_resized_60
        obj.new_image_raw = obj.image_raw
        obj.new_priority = obj.priority
        obj.save()


def unmigrate_voucherimported(apps, schema_editor):
    voucher_imported = apps.get_model('digitalization', 'voucherimported')
    for obj in tqdm(voucher_imported.objects.all()):
        obj.vouchers_file = obj.new_vouchers_file
        obj.biodata_code = obj.new_biodata_code
        obj.image = obj.new_image
        obj.image_resized_10 = obj.new_image_resized_10
        obj.image_resized_60 = obj.new_image_resized_60
        obj.image_public = obj.new_image_public
        obj.image_public_resized_60 = obj.new_image_public_resized_60
        obj.image_raw = obj.new_image_raw
        obj.priority = obj.new_priority
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0018_rename_voucherimported_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherImported',
            fields=[
                ('voucher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='digitalization.voucher')),
                ('new_image', models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.GlacierPrivateMediaStorage(), upload_to='', verbose_name='Image')),
                ('new_image_resized_10', models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.IAPrivateMediaStorage(), upload_to='', verbose_name='Escala de imagen 10 veces más pequeña')),
                ('new_image_resized_60', models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.IAPrivateMediaStorage(), upload_to='', verbose_name='Escala de imagen 60 veces más pequeña')),
                ('new_image_public', models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.PublicMediaStorage(), upload_to='', verbose_name='Public Image')),
                ('new_image_public_resized_60', models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.PublicMediaStorage(), upload_to='', verbose_name='Escala de imagen pública 60 veces más pequeña')),
                ('new_image_raw', models.ImageField(blank=True, null=True, storage=apps.digitalization.storage_backends.GlacierPrivateMediaStorage(), upload_to='', verbose_name='Raw Image')),
                ('new_priority', models.IntegerField(blank=True, default=3, null=True, verbose_name='Priority')),
                ('new_biodata_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalization.biodatacode', verbose_name='BIODATA Code')),
                ('new_vouchers_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalization.priorityvouchersfile', verbose_name='Priority Vouchers File')),
            ],
            bases=('digitalization.voucher',),
        ),
        migrations.RunPython(migrate_voucherimported, unmigrate_voucherimported),
    ]
