# Generated by Django 5.1.6 on 2026-06-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0019_voucherimported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='biodata_code',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='image',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='image_public',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='image_public_resized_60',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='image_raw',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='image_resized_10',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='image_resized_60',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='vouchers_file',
        ),
        migrations.AddField(
            model_name='voucher',
            name='iiif',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IIIF'),
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='new_biodata_code',
            new_name='biodata_code',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='new_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='new_image_public',
            new_name='image_public',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='new_image_public_resized_60',
            new_name='image_public_resized_60',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='new_image_raw',
            new_name='image_raw',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='new_image_resized_10',
            new_name='image_resized_10',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='new_image_resized_60',
            new_name='image_resized_60',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='new_priority',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='voucherimported',
            old_name='new_vouchers_file',
            new_name='vouchers_file',
        ),
    ]
