# Generated by Django 5.1.6 on 2026-06-24 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0020_rename_new_biodata_code_voucherimported_biodata_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherRepatriated',
            fields=[
                ('voucher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='digitalization.voucher')),
                ('verbatim_scientific_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Verbatim Scientific Name')),
                ('rejected', models.BooleanField(default=False, verbose_name='Rejected')),
            ],
            bases=('digitalization.voucher',),
        ),
        migrations.AddField(
            model_name='herbarium',
            name='herbarium_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Managed'), (1, 'Repatriated')], null=True, verbose_name='Type of Herbarium'),
        ),
    ]
