# Generated by Django 5.1.6 on 2026-09-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0021_voucherrepatriated_herbarium_herbarium_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='associated_sequences',
            field=models.URLField(blank=True, null=True, verbose_name='Associated Sequences'),
        ),
    ]
