"""
Django settings for intranet project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", 'false') == 'true'

ALLOWED_HOSTS = ['*']

HERBARIUM_FRONTEND = os.environ.get("HERBARIUM_FRONTEND")


# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'drf_multiple_model',
    'rest_framework',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'leaflet',
    'apps.digitalization',
    'apps.catalog',
    'apps.home',
    'apps.api',
    'apps.metadata',
    'import_export',
    'django_dump_load_utf8',
    'storages',
    'django.contrib.gis',
    'corsheaders',
    'widget_tweaks',
    'django_hosts',
    'ckeditor',
]

MIDDLEWARE = [
    'django_hosts.middleware.HostsRequestMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.home.views.ProfileLanguageMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django_hosts.middleware.HostsResponseMiddleware',
]

ROOT_URLCONF = 'intranet.main_urls'
ROOT_HOSTCONF = 'intranet.hosts'
DEFAULT_HOST = 'digitalization'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'intranet.wsgi.application'

DATA_UPLOAD_MAX_NUMBER_FIELDS = None

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get("POSTGRES_DB"),
        'USER': os.environ.get("POSTGRES_USER"),
        'PASSWORD': os.environ.get("POSTGRES_PASSWORD"),
        'HOST': os.environ.get("POSTGRES_HOST"),
        'PORT': os.environ.get("POSTGRES_PORT"),
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ('es', _('Spanish')),
    ('en', _('English')),
    # ('de', _('German')),
]

LOCALE_PATHS = [
    "intranet/locale",
]

AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME")
AWS_DEFAULT_ACL = os.environ.get("AWS_DEFAULT_ACL", None)
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
USE_SSL = os.environ.get("DJANGO_USE_SSL", 'false') == 'true'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
if DEBUG:
    STATIC_URL = 'static/'
else:
    STORAGES = {
        'staticfiles': {
            'BACKEND': 'apps.digitalization.storage_backends.StaticStorage',
        }
    }
    AWS_STATIC_LOCATION = 'static/digitalization/'
    STATIC_URL = os.environ.get("DIGITALIZATION_STATIC_HOST")

AWS_PUBLIC_MEDIA_LOCATION = 'media/public'
DEFAULT_FILE_STORAGE = 'apps.digitalization.storage_backends.PublicMediaStorage'
MEDIA_URL = os.environ.get("IMAGE_HOST")

AWS_PRIVATE_MEDIA_LOCATION = 'media/private'
PRIVATE_FILE_STORAGE = 'apps.digitalization.storage_backends.PrivateMediaStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGOUT_REDIRECT_URL = "/"

# allow upload big file
DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 60  # 15M
FILE_UPLOAD_MAX_MEMORY_SIZE = DATA_UPLOAD_MAX_MEMORY_SIZE
DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000

# Geographical libraries
GEOS_LIBRARY_PATH = '/usr/lib/x86_64-linux-gnu/libgeos_c.so'
GDAL_LIBRARY_PATH = '/usr/lib/x86_64-linux-gnu/libgdal.so'
PROJ_LIBRARY_PATH = '/usr/lib/x86_64-linux-gnu/libproj.so'

SWAGGER_SETTINGS = {
    'DEFAULT_AUTO_SCHEMA_CLASS': 'drf_yasg.inspectors.SwaggerAutoSchema',
}

CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 24 * 60 * 60
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND")
CELERY_TIMEZONE = TIME_ZONE

CELERY_BEAT_SCHEDULE = {
    'daily_postprocessing': {
        'task': 'scheduled_postprocessing',
        'schedule': crontab(hour="1", minute="0"),
        'args': ('input', 'tmp', 'log')
    },
    'weekly_clean_storage': {
        'task': 'clean_storage',
        'schedule': crontab(hour="3", minute="0", day_of_week='sunday'),
        'args': ('/var/log/clean_storage', )
    }
}

USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
CORS_ORIGIN_ALLOW_ALL = False
if DEBUG:
    CORS_ORIGIN_WHITELIST = (
        HERBARIUM_FRONTEND,
    )
else:
    CORS_ORIGIN_WHITELIST = (
        'https://herbariodigital.cl',
        HERBARIUM_FRONTEND,
    )

CSRF_TRUSTED_ORIGINS = ['https://*.herbariodigital.cl']
CSRF_COOKIE_SECURE = not DEBUG

TAXA_ID_PREF = 'https://catalogoplantas.udec.cl/taxa/'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': (
        'apps.api.renderers.CustomBrowsableAPIRenderer',
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.TemplateHTMLRenderer',
    ),
}

SPECTACULAR_SETTINGS = {
    'TITLE': _("Digital Herbarium API"),
    'DESCRIPTION': _("API description"),
    'VERSION': '1.0.0',
    'CONTACT': {
        'email': "soporte.portal@ieb-chile.cl",
    },
    'LICENSE': {
        'name': _("Mozilla Public License, version 2.0"),
        'url': _("Mozilla MPL URL"),
    },
    'TOS': "https://www.herbariodigital.cl/catalog_about/",
    'SERVE_URLCONF': 'apps.api.urls',
    'SWAGGER_UI_DIST': 'SIDECAR',  # shorthand to use the sidecar instead
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
}

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_PORT = os.environ.get("EMAIL_PORT")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", 'false') == 'true'
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", 'false') == 'true'

LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (-39.8232657, -73.261518),
    'DEFAULT_ZOOM': 4,
    'TILES': [
        ('Custom Tiles', 'https://{s}.google.com/vt/lyrs=s,h&x={x}&y={y}&z={z}', {
            'maxZoom': 20,
            'subdomains': ['mt0', 'mt1', 'mt2', 'mt3'],
        }),
    ],
    'RESET_VIEW': False,
    'PLUGINS': {
        'draw': {
            'css': 'https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.css',
            'js': 'https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.js',
        },
        'forms': {
            'auto-include': True,
        },
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'handlers': {
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'gunicorn',
        },
    },
    'formatters': {
        'gunicorn': {
            'format': '[%(asctime)s] [%(process)d] [%(levelname)s] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S %z',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}
