# Generated by Django 5.1.6 on 2025-02-19 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalization', '0010_typestatus'),
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emldataset',
            name='geographic_coverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.geographiccoverage', verbose_name='Geographic Coverage'),
        ),
        migrations.AlterField(
            model_name='emldataset',
            name='intellectual_rights',
            field=models.TextField(blank=True, null=True, verbose_name='Intellectual Rights'),
        ),
        migrations.AlterField(
            model_name='emldataset',
            name='keyword_set',
            field=models.ManyToManyField(blank=True, to='metadata.keywordset', verbose_name='Keyword Set'),
        ),
        migrations.AlterField(
            model_name='emldataset',
            name='licensed',
            field=models.ManyToManyField(blank=True, to='digitalization.licence', verbose_name='Licenced'),
        ),
        migrations.AlterField(
            model_name='emldataset',
            name='metadata_provider',
            field=models.ManyToManyField(blank=True, related_name='metadata_provider', to='metadata.responsibleparty', verbose_name='Metadata Provider'),
        ),
        migrations.AlterField(
            model_name='emldataset',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='method', to='metadata.method', verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='emldataset',
            name='taxonomic_coverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.taxonomiccoverage', verbose_name='Taxonomic Coverage'),
        ),
        migrations.AlterField(
            model_name='procedurestep',
            name='sub_step',
            field=models.ManyToManyField(blank=True, to='metadata.procedurestep', verbose_name='Sub Step'),
        ),
    ]
