# Generated by Django 5.1.6 on 2025-02-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_alter_emldataset_geographic_coverage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='type',
            field=models.IntegerField(choices=[(0, 'NULL'), (1, 'PLACE'), (2, 'STRATUM'), (4, 'TEMPORAL'), (5, 'THEME'), (6, 'TAXONOMIC')], default=0, verbose_name='Type'),
        ),
    ]
