# Generated by Django 5.1.6 on 2025-04-11 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_alter_keyword_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='Name')),
                ('name_es', models.CharField(max_length=300, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=300, null=True, verbose_name='Name')),
                ('link', models.CharField(blank=True, max_length=300, null=True, verbose_name='Link')),
                ('short_name', models.CharField(max_length=20, null=True, verbose_name='Short Name')),
                ('added_by', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
            ],
        ),
        migrations.AlterField(
            model_name='emldataset',
            name='licensed',
            field=models.ManyToManyField(blank=True, to='metadata.licence', verbose_name='Licenced'),
        ),
    ]
