# Generated by Django 4.2.6 on 2024-07-18 21:16

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=5, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(blank=True, choices=[('light', 'Light')], default='light', max_length=16, null=True, verbose_name='Theme'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor.fields.RichTextField(verbose_name='Message')),
                ('message_es', ckeditor.fields.RichTextField(null=True, verbose_name='Message')),
                ('message_en', ckeditor.fields.RichTextField(null=True, verbose_name='Message')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
            },
        ),
    ]
