# Generated by Django 5.1.6 on 2025-08-06 20:22

import apps.digitalization.storage_backends
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_profile_language_alter_profile_theme_alert'),
        ('metadata', '0004_licence_alter_emldataset_licensed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarwinCoreArchiveFile',
            fields=[
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='metadata.eml', verbose_name='Metadata File')),
                ('file', models.FileField(storage=apps.digitalization.storage_backends.PrivateMediaStorage(), upload_to='darwin_core_archive', verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
    ]
