# -*- coding: utf-8 -*-

from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^download$', views.catalog_download, name='catalog_download'),   
    re_path(r'^list_division$', views.list_division, name='list_division'),
    re_path(r'^division_table$', views.division_table, name='division_table'),
    re_path(r'^create_division$', views.create_division, name='create_division'),
    re_path(r'^update_division/(?P<division_id>\d+)/$', views.update_division, name='update_division'),
    re_path(r'^list_class$', views.list_class, name='list_class'),
    re_path(r'^class_table$', views.class_table, name='class_table'),
    re_path(r'^create_class$', views.create_class, name='create_class'),
    re_path(r'^update_class/(?P<class_id>\d+)/$', views.update_class, name='update_class'),
    re_path(r'^list_order$', views.list_order, name='list_order'),
    re_path(r'^order_table$', views.order_table, name='order_table'),
    re_path(r'^create_order$', views.create_order, name='create_order'),
    re_path(r'^update_order/(?P<order_id>\d+)/$', views.update_order, name='update_order'),
    re_path(r'^list_family$', views.list_family, name='list_family'),
    re_path(r'^family_table$', views.family_table, name='family_table'),
    re_path(r'^create_family$', views.create_family, name='create_family'),
    re_path(r'^update_family/(?P<family_id>\d+)/$', views.update_family, name='update_family'),
    re_path(r'^list_genus$', views.list_genus, name='list_genus'),
    re_path(r'^genus_table$', views.genus_table, name='genus_table'),
    re_path(r'^create_genus$', views.create_genus, name='create_genus'),
    re_path(r'^update_genus/(?P<genus_id>\d+)/$', views.update_genus, name='update_genus'),
    re_path(r'^update_genus_family/(?P<genus_id>\d+)/$', views.update_genus_family, name='update_genus_family'),
    re_path(r'^proposal_genus/(?P<genus_id>\d+)/$', views.proposal_genus, name='proposal_genus'),
    re_path(r'^list_taxa$', views.list_taxa, name='list_taxa'),
    re_path(r'^taxa_table$', views.taxa_table, name='taxa_table'),
    re_path(r'^create_taxa$', views.create_taxa, name='create_taxa'),
    re_path(r'^update_taxa/(?P<species_id>\d+)/$', views.update_taxa, name='update_taxa'),
    re_path(r'^delete_taxa/(?P<species_id>\d+)/$', views.delete_taxa, name='delete_taxa'),
    # TODO: Refactor this:
    re_path(r'^merge_taxa/(?P<id>\d+)/$', views.merge_taxa, name='merge_taxa'),
    re_path(r'^split_1_taxa/(?P<specie_id>\d+)/$', views.split_1_taxa, name='split_1_taxa'),
    re_path(r'^split_2_taxa/(?P<id>\d+)/$', views.split_2_taxa, name='split_2_taxa'),
    re_path(r'^get_taxa/(?P<id>\d+)/$', views.get_taxa, name='get_taxa'),
    # ===>
    re_path(r'^list_synonymy$', views.list_synonymy, name='list_synonymy'),
    re_path(r'^synonymy_table$', views.synonymy_table, name='synonymy_table'),
    re_path(r'^create_synonymy$', views.create_synonymy, name='create_synonymy'),
    re_path(r'^update_synonymy/(?P<synonymy_id>\d+)/$', views.update_synonymy, name='update_synonymy'),
    re_path(r'^delete_synonymy/(?P<synonymy_id>\d+)/$', views.delete_synonymy, name='delete_synonymy'),
    re_path(r'^list_binnacle$', views.list_binnacle, name='list_binnacle'),
    re_path(r'^update_binnacle/(?P<binnacle_id>\d+)/$', views.update_binnacle, name='update_binnacle'),
    re_path(r'^list_common_name$', views.list_common_name, name='list_common_name'),
    re_path(r'^common_name_table$', views.common_name_table, name='common_name_table'),
    re_path(r'^create_common_name$', views.create_common_name, name='create_common_name'),
    re_path(r'^update_common_name/(?P<common_id>\d+)/$', views.update_common_name, name='update_common_name'),
    re_path(r'^delete_common_name/(?P<common_id>\d+)/$', views.delete_common_name, name='delete_common_name'),
]
