# Generated by Django 4.1.7 on 2023-04-20 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conservationstate',
            name='order',
            field=models.IntegerField(blank=True, db_column='order', null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order', help_text='order', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.order'),
        ),
        migrations.AlterField(
            model_name='region',
            name='order',
            field=models.IntegerField(blank=True, db_column='order', null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='region',
            field=models.ManyToManyField(blank=True, db_column='region', to='catalog.region'),
        ),
    ]
