# Generated by Django 4.2.6 on 2023-10-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinderView',
            fields=[
                ('id', models.IntegerField(help_text='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='name', max_length=500, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('determined', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'finder_view',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW finder_view AS
            SELECT id, 'species' AS type, scientific_name AS name, determined FROM catalog_species
            UNION ALL
            SELECT id, 'synonymy' AS type, scientific_name AS name, FALSE AS determined FROM catalog_synonymy
            UNION ALL
            SELECT id, 'family' AS type, name, FALSE AS determined FROM catalog_family
            UNION ALL
            SELECT id, 'genus' AS type, name, FALSE AS determined FROM catalog_genus
            UNION ALL
            SELECT id, 'common_name' AS type, name, FALSE AS determined FROM catalog_commonname
            ORDER BY type, name;
            """
        ),
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX finder_view_id
                ON finder_view (id, type);
            """
        ),
        migrations.RunSQL(
            """
            CREATE INDEX finder_view_trgm_id
                ON finder_view USING gin(name gin_trgm_ops);
            """
        ),
    ]
