# Generated by Django 4.1.7 on 2023-04-22 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conservationstate',
            name='order',
            field=models.IntegerField(blank=True, db_column='order', null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order', help_text='order', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.order'),
        ),
        migrations.AlterField(
            model_name='region',
            name='order',
            field=models.IntegerField(blank=True, db_column='order', null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='habit',
            field=models.ForeignKey(blank=True, db_column='habit', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.habit'),
        ),
        migrations.AlterField(
            model_name='species',
            name='region',
            field=models.ManyToManyField(blank=True, db_column='region', to='catalog.region'),
        ),
        migrations.CreateModel(
            name='PlantHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Plant Habits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('female_name', models.CharField(blank=True, max_length=100, null=True)),
                ('male_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Environmental Habits',
                'ordering': ['female_name'],
            },
        ),
        migrations.AddField(
            model_name='species',
            name='env_habit',
            field=models.ManyToManyField(blank=True, db_column='environmental_habit', to='catalog.environmentalhabit'),
        ),
        migrations.AddField(
            model_name='species',
            name='plant_habit',
            field=models.ManyToManyField(blank=True, db_column='plant_habit', to='catalog.planthabit'),
        ),
    ]
