# Generated by Django 4.2.6 on 2023-11-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_finderview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environmentalhabit',
            options={'ordering': ['name'], 'verbose_name_plural': 'Environmental Habits'},
        ),
        migrations.RenameField(
            model_name='environmentalhabit',
            old_name='female_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='environmentalhabit',
            name='male_name',
        ),
        migrations.AddField(
            model_name='binnacle',
            name='description_en',
            field=models.CharField(blank=True, help_text='descripción', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='binnacle',
            name='description_es',
            field=models.CharField(blank=True, help_text='descripción', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='binnacle',
            name='model_en',
            field=models.CharField(blank=True, help_text='modelo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='binnacle',
            name='model_es',
            field=models.CharField(blank=True, help_text='modelo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='binnacle',
            name='note_en',
            field=models.CharField(blank=True, help_text='descripción', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='binnacle',
            name='note_es',
            field=models.CharField(blank=True, help_text='descripción', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='binnacle',
            name='type_update_en',
            field=models.CharField(blank=True, help_text='tipo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='binnacle',
            name='type_update_es',
            field=models.CharField(blank=True, help_text='tipo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commonname',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='commonname',
            name='name_es',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='conservationstate',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='conservationstate',
            name='name_es',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='environmentalhabit',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='environmentalhabit',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planthabit',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planthabit',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_es',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='name_es',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
