# Generated by Django 4.1.7 on 2023-04-20 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_conservationstate_order_alter_family_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='habit',
            field=models.ForeignKey(blank=True, db_column='habit', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.habit'),
        ),
    ]
