# Generated by Django 4.1.7 on 2023-04-26 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_alter_conservationstate_order_alter_family_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ciclos',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='habit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='species',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='species',
            name='habit',
        ),
        migrations.DeleteModel(
            name='Ciclo',
        ),
        migrations.DeleteModel(
            name='Habit',
        ),
        migrations.AddField(
            model_name='species',
            name='cycle',
            field=models.ManyToManyField(blank=True, db_column='cycle', to='catalog.cycle'),
        ),
    ]
