# Generated by Django 4.2.6 on 2023-12-02 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_alter_environmentalhabit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ['name'], 'verbose_name_plural': 'Cycles'},
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('name_es', models.CharField(blank=True, max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('env_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.environmentalhabit')),
                ('plant_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.planthabit')),
            ],
            options={
                'verbose_name_plural': 'Habits',
                'ordering': ['plant_habit', 'env_habit'],
            },
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.UniqueConstraint(fields=('plant_habit', 'env_habit'), name='unique habit'),
        ),
    ]
