# Generated by Django 4.2.6 on 2023-12-28 14:17

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_alter_cycle_options_habit_habit_unique_habit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classname',
            options={'default_related_name': 'class_name', 'ordering': ['name'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='commonname',
            options={'ordering': ['name'], 'verbose_name': 'Common Name', 'verbose_name_plural': 'Common Names'},
        ),
        migrations.AlterModelOptions(
            name='conservationstate',
            options={'ordering': ['order'], 'verbose_name': 'Conservation State', 'verbose_name_plural': 'Conservation States'},
        ),
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ['name'], 'verbose_name': 'Cycle', 'verbose_name_plural': 'Cycles'},
        ),
        migrations.AlterModelOptions(
            name='environmentalhabit',
            options={'ordering': ['name'], 'verbose_name': 'Environmental Habit', 'verbose_name_plural': 'Environmental Habits'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['name'], 'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='genus',
            options={'ordering': ['name'], 'verbose_name': 'Genus', 'verbose_name_plural': 'Genera'},
        ),
        migrations.AlterModelOptions(
            name='kingdom',
            options={'ordering': ['name'], 'verbose_name': 'Kingdom', 'verbose_name_plural': 'Kingdoms'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['name'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='planthabit',
            options={'ordering': ['name'], 'verbose_name': 'Plant Habit', 'verbose_name_plural': 'Plant Habits'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['order'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['scientific_name'], 'verbose_name': 'Species', 'verbose_name_plural': 'Species'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name'], 'verbose_name': 'Origin', 'verbose_name_plural': 'Origins'},
        ),
        migrations.AlterModelOptions(
            name='synonymy',
            options={'ordering': ['scientific_name'], 'verbose_name': 'Synonym', 'verbose_name_plural': 'Synonyms'},
        ),
        migrations.AddField(
            model_name='region',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Geometry'),
        ),
        migrations.AlterField(
            model_name='classname',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='classname',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='classname',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.division', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='classname',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='classname',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='commonname',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='commonname',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='commonname',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='commonname',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='commonname',
            name='name_es',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='commonname',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='conservationstate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='conservationstate',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='conservationstate',
            name='key',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='conservationstate',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='conservationstate',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='conservationstate',
            name='name_es',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='conservationstate',
            name='order',
            field=models.IntegerField(blank=True, db_column='order', null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='conservationstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='name_es',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='division',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='division',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='division',
            name='kingdom',
            field=models.ForeignKey(blank=True, help_text='Reino', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.kingdom', verbose_name='Kingdom'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='division',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='environmentalhabit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='environmentalhabit',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='environmentalhabit',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='environmentalhabit',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='environmentalhabit',
            name='name_es',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='environmentalhabit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='family',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='family',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='family',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order', help_text='order', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='family',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='family',
            field=models.ForeignKey(blank=True, help_text='Familia', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.family', verbose_name='Family'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name_es',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='kingdom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='kingdom',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='kingdom',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='kingdom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='class_name',
            field=models.ForeignKey(blank=True, help_text='Clase', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.classname', verbose_name='Class Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='planthabit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='planthabit',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='planthabit',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='planthabit',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='planthabit',
            name='name_es',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='planthabit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='region',
            name='key',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_es',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='region',
            name='order',
            field=models.IntegerField(blank=True, db_column='order', null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='region',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='species',
            name='common_names',
            field=models.ManyToManyField(blank=True, to='catalog.commonname', verbose_name='Common names'),
        ),
        migrations.AlterField(
            model_name='species',
            name='conservation_state',
            field=models.ManyToManyField(blank=True, to='catalog.conservationstate', verbose_name='Conservation State'),
        ),
        migrations.AlterField(
            model_name='species',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='species',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='species',
            name='cycle',
            field=models.ManyToManyField(blank=True, db_column='cycle', to='catalog.cycle', verbose_name='Cycle'),
        ),
        migrations.AlterField(
            model_name='species',
            name='determined',
            field=models.BooleanField(default=False, verbose_name='Determined?'),
        ),
        migrations.AlterField(
            model_name='species',
            name='env_habit',
            field=models.ManyToManyField(blank=True, db_column='environmental_habit', to='catalog.environmentalhabit', verbose_name='Life Form'),
        ),
        migrations.AlterField(
            model_name='species',
            name='form',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Form'),
        ),
        migrations.AlterField(
            model_name='species',
            name='form_authorship',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Form Authorship'),
        ),
        migrations.AlterField(
            model_name='species',
            name='genus',
            field=models.ForeignKey(blank=True, help_text='Genus', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genus', verbose_name='Genus'),
        ),
        migrations.AlterField(
            model_name='species',
            name='id_mma',
            field=models.IntegerField(blank=True, help_text='ID of the species platform of the MMA', null=True, verbose_name='MMA ID'),
        ),
        migrations.AlterField(
            model_name='species',
            name='id_taxa',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Taxa'),
        ),
        migrations.AlterField(
            model_name='species',
            name='id_taxa_origin',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Taxa of Origin'),
        ),
        migrations.AlterField(
            model_name='species',
            name='in_argentina',
            field=models.BooleanField(default=False, verbose_name='In Argentina'),
        ),
        migrations.AlterField(
            model_name='species',
            name='in_bolivia',
            field=models.BooleanField(default=False, verbose_name='In Bolivia'),
        ),
        migrations.AlterField(
            model_name='species',
            name='in_peru',
            field=models.BooleanField(default=False, verbose_name='In Peru'),
        ),
        migrations.AlterField(
            model_name='species',
            name='maximum_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Height'),
        ),
        migrations.AlterField(
            model_name='species',
            name='minimum_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Height'),
        ),
        migrations.AlterField(
            model_name='species',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='species',
            name='pages',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Pages'),
        ),
        migrations.AlterField(
            model_name='species',
            name='plant_habit',
            field=models.ManyToManyField(blank=True, db_column='plant_habit', to='catalog.planthabit', verbose_name='Habit'),
        ),
        migrations.AlterField(
            model_name='species',
            name='publication',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Publication'),
        ),
        migrations.AlterField(
            model_name='species',
            name='region',
            field=models.ManyToManyField(blank=True, db_column='region', to='catalog.region', verbose_name='Regions'),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Scientific Name'),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name_authorship',
            field=models.CharField(blank=True, help_text='AutoresSp', max_length=500, null=True, verbose_name='Scientific Name Authorship'),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name_db',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Scientific Name Database'),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name_full',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Complete Scientific Name'),
        ),
        migrations.AlterField(
            model_name='species',
            name='specific_epithet',
            field=models.CharField(blank=True, help_text='EpitetoEspecifico', max_length=300, null=True, verbose_name='Specific Epithet'),
        ),
        migrations.AlterField(
            model_name='species',
            name='ssp_authorship',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Subspecies Authorship'),
        ),
        migrations.AlterField(
            model_name='species',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='species',
            name='subspecies',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Subspecies'),
        ),
        migrations.AlterField(
            model_name='species',
            name='synonyms',
            field=models.ManyToManyField(blank=True, to='catalog.synonymy', verbose_name='Synonyms'),
        ),
        migrations.AlterField(
            model_name='species',
            name='type_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Type ID'),
        ),
        migrations.AlterField(
            model_name='species',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='species',
            name='variety',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Variety'),
        ),
        migrations.AlterField(
            model_name='species',
            name='variety_authorship',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Variety Authorship'),
        ),
        migrations.AlterField(
            model_name='species',
            name='volume',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='species',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='status',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name_es',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='status',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='synonymy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='synonymy',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='synonymy',
            name='form',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Form'),
        ),
        migrations.AlterField(
            model_name='synonymy',
            name='form_authorship',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Form Authorship'),
        ),
        migrations.AlterField(
            model_name='synonymy',
            name='genus',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Genus'),
        ),
        migrations.AlterField(
            model_name='synonymy',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Scientific Name'),
        ),
        migrations.AlterField(
            model_name='synonymy',
            name='scientific_name_authorship',
            field=models.CharField(blank=True, help_text='AutoresSp', max_length=500, null=True, verbose_name='Scientific Name Authorship'),
        ),
        migrations.AlterField(
            model_name='synonymy',
            name='scientific_name_db',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Scientific Name Database'),
        ),
        migrations.AlterField(
            model_name='synonymy',
            name='scientific_name_full',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Complete Scientific Name'),
        ),
        migrations.AlterField(
            model_name='synonymy',
            name='specific_epithet',
            field=models.CharField(blank=True, help_text='EpitetoEspecifico', max_length=300, null=True, verbose_name='Specific Epithet'),
        ),
        migrations.AlterField(
            model_name='synonymy',
            name='ssp_authorship',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Subspecies Authorship'),
        ),
        migrations.AlterField(
            model_name='synonymy',
            name='subspecies',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Subspecies'),
        ),
        migrations.AlterField(
            model_name='synonymy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='synonymy',
            name='variety',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Variety'),
        ),
        migrations.AlterField(
            model_name='synonymy',
            name='variety_authorship',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Variety Authorship'),
        ),
    ]
