# Generated by Django 4.2.6 on 2024-05-31 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_binnacle_description_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE SEQUENCE IF NOT EXISTS taxa_id_seq;
            """,
            reverse_sql="DROP SEQUENCE IF EXISTS taxa_id_seq;"
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION get_taxa_id() RETURNS BIGINT AS $$
            BEGIN
                RETURN nextval('taxa_id_seq');
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS get_taxa_id();"
        )
    ]
