# Generated by Django 4.2.6 on 2024-05-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20240531_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='classname',
            name='taxa_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classname',
            name='taxa_num_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='taxa_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='taxa_num_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='taxa_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='taxa_num_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genus',
            name='taxa_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genus',
            name='taxa_num_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='taxa_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='taxa_num_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='taxa_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='taxa_num_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='taxa_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='taxa_num_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synonymy',
            name='taxa_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synonymy',
            name='taxa_num_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
