# Generated by Django 4.2.6 on 2024-05-31 15:52

from django.db import migrations


def set_default_values(apps, schema_editor):
    schema_editor.execute("""
    ALTER TABLE catalog_class_name ALTER COLUMN taxa_num_id SET DEFAULT get_taxa_id();
    """)
    schema_editor.execute("""
    ALTER TABLE catalog_division ALTER COLUMN taxa_num_id SET DEFAULT get_taxa_id();
    """)
    schema_editor.execute("""
    ALTER TABLE catalog_family ALTER COLUMN taxa_num_id SET DEFAULT get_taxa_id();
    """)
    schema_editor.execute("""
    ALTER TABLE catalog_genus ALTER COLUMN taxa_num_id SET DEFAULT get_taxa_id();
    """)
    schema_editor.execute("""
    ALTER TABLE catalog_kingdom ALTER COLUMN taxa_num_id SET DEFAULT get_taxa_id();
    """)
    schema_editor.execute("""
    ALTER TABLE catalog_order ALTER COLUMN taxa_num_id SET DEFAULT get_taxa_id();
    """)
    schema_editor.execute("""
    ALTER TABLE catalog_species ALTER COLUMN taxa_num_id SET DEFAULT get_taxa_id();
    """)
    schema_editor.execute("""
    ALTER TABLE catalog_synonymy ALTER COLUMN taxa_num_id SET DEFAULT get_taxa_id();
    """)


def unset_default_values(apps, schema_editor):
    schema_editor.execute("""
    ALTER TABLE catalog_class_name ALTER COLUMN taxa_num_id DROP DEFAULT;
    """)
    schema_editor.execute("""
    ALTER TABLE catalog_division ALTER COLUMN taxa_num_id DROP DEFAULT;
    """)
    schema_editor.execute("""
    ALTER TABLE catalog_family ALTER COLUMN taxa_num_id DROP DEFAULT;
    """)
    schema_editor.execute("""
    ALTER TABLE catalog_genus ALTER COLUMN taxa_num_id DROP DEFAULT;
    """)
    schema_editor.execute("""
    ALTER TABLE catalog_kingdom ALTER COLUMN taxa_num_id DROP DEFAULT;
    """)
    schema_editor.execute("""
    ALTER TABLE catalog_order ALTER COLUMN taxa_num_id DROP DEFAULT;
    """)
    schema_editor.execute("""
    ALTER TABLE catalog_species ALTER COLUMN taxa_num_id DROP DEFAULT;
    """)
    schema_editor.execute("""
    ALTER TABLE catalog_synonymy ALTER COLUMN taxa_num_id DROP DEFAULT;
    """)


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0008_classname_taxa_id_classname_taxa_num_id_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_values, unset_default_values),
    ]
