# Generated by Django 4.2.6 on 2024-05-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20240531_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='taxa_id',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='classname',
            name='taxa_num_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='division',
            name='taxa_id',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='division',
            name='taxa_num_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='family',
            name='taxa_id',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='family',
            name='taxa_num_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='genus',
            name='taxa_id',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='genus',
            name='taxa_num_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='kingdom',
            name='taxa_id',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='kingdom',
            name='taxa_num_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxa_id',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxa_num_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='species',
            name='taxa_id',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='species',
            name='taxa_num_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='synonymy',
            name='taxa_id',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='synonymy',
            name='taxa_num_id',
            field=models.BigIntegerField(),
        ),
    ]
