# Generated by Django 4.2.6 on 2024-05-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_classname_taxa_id_alter_classname_taxa_num_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='CatalogView',
            name='taxa_num_id',
            field=models.BigIntegerField()
        ),
        migrations.AddField(
            model_name='CatalogView',
            name='taxa_id',
            field=models.CharField()
        ),
        migrations.AddField(
            model_name='SynonymyView',
            name='taxa_num_id',
            field=models.BigIntegerField()
        ),
        migrations.AddField(
            model_name='SynonymyView',
            name='taxa_id',
            field=models.CharField()
        ),
        migrations.RunSQL(
            """
            DROP MATERIALIZED VIEW catalog_view;
            """
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW catalog_view AS
            SELECT species.id,
                   species.id_taxa,
                   species.taxa_num_id,
                   species.taxa_id,
                   kingdom.id      AS kingdom_id,
                   kingdom.name    AS kingdom,
                   division.id     AS division_id,
                   division.name   AS division,
                   class.id        AS class_name_id,
                   class.name      AS class_name,
                   "order".id      AS order_id,
                   "order".name    AS "order",
                   family.id       AS family_id,
                   family.name     AS family,
                   genus.id        AS genus_id,
                   genus.name      AS genus,
                   species.scientific_name,
                   species.scientific_name_full,
                   species.specific_epithet,
                   species.scientific_name_authorship,
                   species.subspecies,
                   species.ssp_authorship,
                   species.variety,
                   species.variety_authorship,
                   species.form,
                   species.form_authorship,
                   species.in_argentina,
                   species.in_bolivia,
                   species.in_peru,
                   status.name     AS status,
                   status.name_es  AS status_es,
                   status.name_en  AS status_en,
                   species.minimum_height,
                   species.maximum_height,
                   species.notes,
                   species.type_id,
                   species.publication,
                   species.volume,
                   species.pages,
                   species.year,
                   species.determined,
                   species.id_taxa_origin,
                   species.created_at,
                   species.updated_at,
                   "user".username AS created_by
            FROM catalog_species species
                 JOIN auth_user "user" ON species.created_by_id = "user".id
                 JOIN catalog_genus genus ON species.genus_id = genus.id
                 JOIN catalog_family family ON genus.family_id = family.id
                 JOIN catalog_order "order" ON family."order" = "order".id
                 JOIN catalog_class_name class ON "order".class_name_id = class.id
                 JOIN catalog_division division ON class.division_id = division.id
                 JOIN catalog_kingdom kingdom ON division.kingdom_id = kingdom.id
                 LEFT JOIN catalog_status status ON species.status_id = status.id;
            """
        ),
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX catalog_view_id_idx
                ON catalog_view (id);
            """
        ),
        migrations.RunSQL(
            """
            DROP MATERIALIZED VIEW synonymy_view;
            """
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW synonymy_view AS
            SELECT synonymy.id,
                   species.id               AS specie_id,
                   species.id_taxa,
                   synonymy.taxa_num_id,
                   synonymy.taxa_id,
                   species.scientific_name AS specie_scientific_name,
                   species_synonymy.id      AS synonymy_id,
                   synonymy.scientific_name,
                   synonymy.scientific_name_full,
                   synonymy.genus,
                   synonymy.specific_epithet,
                   synonymy.scientific_name_authorship,
                   synonymy.subspecies,
                   synonymy.ssp_authorship,
                   synonymy.variety,
                   synonymy.variety_authorship,
                   synonymy.form,
                   synonymy.form_authorship,
                   synonymy.created_at,
                   synonymy.updated_at,
                   "user".username          AS created_by
            FROM catalog_synonymy synonymy
                LEFT JOIN catalog_species_synonyms species_synonymy ON species_synonymy.synonymy_id = synonymy.id
                LEFT JOIN catalog_species species ON species_synonymy.species_id = species.id
                LEFT JOIN auth_user "user" ON synonymy.created_by_id = "user".id;
            """
        ),
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX synonymy_view_id_idx
                ON synonymy_view (synonymy_id);
            """
        )
    ]
