# Generated by Django 4.2.6 on 2024-05-31 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20240531_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='synonymy',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='synonyms', to='catalog.species', verbose_name='Species'),
        ),
        migrations.RunSQL(
            """
            UPDATE catalog_synonymy
            SET species_id = sp_syn.species_id
            FROM catalog_species_synonyms sp_syn
            WHERE catalog_synonymy.id = sp_syn.synonymy_id;
            """
        ),
        migrations.RemoveField(
            model_name='species',
            name='synonyms',
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW synonymy_view AS
            SELECT synonymy.id,
                   species_id,
                   species.id_taxa,
                   species.scientific_name AS species_scientific_name,
                   synonymy.scientific_name,
                   synonymy.scientific_name_full,
                   synonymy.genus,
                   synonymy.specific_epithet,
                   synonymy.scientific_name_authorship,
                   synonymy.subspecies,
                   synonymy.ssp_authorship,
                   synonymy.variety,
                   synonymy.variety_authorship,
                   synonymy.form,
                   synonymy.form_authorship,
                   synonymy.created_at,
                   synonymy.updated_at,
                   "user".username          AS created_by
            FROM catalog_synonymy synonymy
                LEFT JOIN catalog_species species ON synonymy.species_id = species.id
                LEFT JOIN auth_user "user" ON synonymy.created_by_id = "user".id;
            """
        ),
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX synonymy_view_id_idx
                ON synonymy_view (id);
            """
        ),
]
