# Generated by Django 4.2.6 on 2024-05-31 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20240531_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='synonymy',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='synonyms', to='catalog.species', verbose_name='Species'),
        ),
        migrations.RunSQL(
            """
            UPDATE catalog_synonymy
            SET species_id = sp_syn.species_id
            FROM catalog_species_synonyms sp_syn
            WHERE catalog_synonymy.id = sp_syn.synonymy_id;
            """
        ),
        migrations.RemoveField(
            model_name='species',
            name='synonyms',
        ),
        migrations.RunSQL(
            """
            DROP MATERIALIZED VIEW synonymy_view;
            """
        ),
        migrations.RunSQL(
            """
            
            """
        ),
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX synonymy_view_id_idx
                ON synonymy_view (synonymy_id);
            """
        ),
    ]
