# Generated by Django 4.2.6 on 2024-06-28 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0013_remove_species_synonyms_synonymy_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Name')),
                ('name_es', models.CharField(blank=True, max_length=300, null=True, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Taxon Rank',
                'verbose_name_plural': 'Taxon Rank',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='species',
            name='taxon_rank',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.taxonrank', verbose_name='Taxon Rank'),
        ),
        migrations.AddField(
            model_name='synonymy',
            name='taxon_rank',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.taxonrank', verbose_name='Taxon Rank'),
        ),
    ]
