# Generated by Django 4.2.6 on 2024-07-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_taxonrank_species_taxon_rank_synonymy_taxon_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classname',
            options={'ordering': ['name'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.RenameField(
            model_name='classname',
            old_name='taxa_id',
            new_name='taxon_id',
        ),
        migrations.RenameField(
            model_name='classname',
            old_name='taxa_num_id',
            new_name='unique_taxon_id',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='taxa_id',
            new_name='taxon_id',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='taxa_num_id',
            new_name='unique_taxon_id',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='taxa_id',
            new_name='taxon_id',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='taxa_num_id',
            new_name='unique_taxon_id',
        ),
        migrations.RenameField(
            model_name='genus',
            old_name='taxa_id',
            new_name='taxon_id',
        ),
        migrations.RenameField(
            model_name='genus',
            old_name='taxa_num_id',
            new_name='unique_taxon_id',
        ),
        migrations.RenameField(
            model_name='kingdom',
            old_name='taxa_id',
            new_name='taxon_id',
        ),
        migrations.RenameField(
            model_name='kingdom',
            old_name='taxa_num_id',
            new_name='unique_taxon_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='class_name',
            new_name='classname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='taxa_id',
            new_name='taxon_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='taxa_num_id',
            new_name='unique_taxon_id',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='taxa_id',
            new_name='taxon_id',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='taxa_num_id',
            new_name='unique_taxon_id',
        ),
        migrations.RenameField(
            model_name='synonymy',
            old_name='taxa_id',
            new_name='taxon_id',
        ),
        migrations.RenameField(
            model_name='synonymy',
            old_name='taxa_num_id',
            new_name='unique_taxon_id',
        ),
        migrations.AlterModelTable(
            name='classname',
            table=None,
        ),
        migrations.RunSQL(
            """
            DROP MATERIALIZED VIEW catalog_view;
            """
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW catalog_view AS
            SELECT species.id,
                   species.id_taxa,
                   species.unique_taxon_id,
                   species.taxon_id,
                   kingdom.id      AS kingdom_id,
                   kingdom.name    AS kingdom,
                   division.id     AS division_id,
                   division.name   AS division,
                   classname.id    AS classname_id,
                   classname.name  AS classname,
                   "order".id      AS order_id,
                   "order".name    AS "order",
                   family.id       AS family_id,
                   family.name     AS family,
                   genus.id        AS genus_id,
                   genus.name      AS genus,
                   species.scientific_name,
                   species.scientific_name_full,
                   species.specific_epithet,
                   species.scientific_name_authorship,
                   species.subspecies,
                   species.ssp_authorship,
                   species.variety,
                   species.variety_authorship,
                   species.form,
                   species.form_authorship,
                   species.in_argentina,
                   species.in_bolivia,
                   species.in_peru,
                   status.name     AS status,
                   status.name_es  AS status_es,
                   status.name_en  AS status_en,
                   species.minimum_height,
                   species.maximum_height,
                   species.notes,
                   species.type_id,
                   species.publication,
                   species.volume,
                   species.pages,
                   species.year,
                   species.determined,
                   species.id_taxa_origin,
                   species.created_at,
                   species.updated_at,
                   "user".username AS created_by
            FROM catalog_species species
                 JOIN auth_user "user" ON species.created_by_id = "user".id
                 JOIN catalog_genus genus ON species.genus_id = genus.id
                 JOIN catalog_family family ON genus.family_id = family.id
                 JOIN catalog_order "order" ON family."order" = "order".id
                 JOIN catalog_classname classname ON "order".classname_id = classname.id
                 JOIN catalog_division division ON classname.division_id = division.id
                 JOIN catalog_kingdom kingdom ON division.kingdom_id = kingdom.id
                 LEFT JOIN catalog_status status ON species.status_id = status.id;
            """
        ),
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX catalog_view_id_idx
                ON catalog_view (id);
            """
        ),
        migrations.RunSQL(
            """
            DROP MATERIALIZED VIEW synonymy_view;
            """
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW synonymy_view AS
            SELECT synonymy.id,
                   species_id,
                   species.id_taxa,
                   species.scientific_name AS species_scientific_name,
                   synonymy.scientific_name,
                   synonymy.scientific_name_full,
                   synonymy.genus,
                   synonymy.specific_epithet,
                   synonymy.scientific_name_authorship,
                   synonymy.subspecies,
                   synonymy.ssp_authorship,
                   synonymy.variety,
                   synonymy.variety_authorship,
                   synonymy.form,
                   synonymy.form_authorship,
                   synonymy.created_at,
                   synonymy.updated_at,
                   "user".username          AS created_by
            FROM catalog_synonymy synonymy
                LEFT JOIN catalog_species species ON synonymy.species_id = species.id
                LEFT JOIN auth_user "user" ON synonymy.created_by_id = "user".id;
            """,
        ),
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX synonymy_view_id_idx
                ON synonymy_view (id);
            """
        ),
        migrations.RunSQL(
            """
            ALTER SEQUENCE taxa_id_seq RENAME TO taxon_id_seq;
            """
        ),
        migrations.RunSQL(
            """
            ALTER FUNCTION get_taxa_id() RENAME TO get_taxon_id;
            """
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION get_taxon_id() RETURNS BIGINT AS $$
            BEGIN
                RETURN nextval('taxon_id_seq');
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS get_taxon_id();"
        )
    ]
