# Generated by Django 4.2.6 on 2024-07-19 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_classname_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP MATERIALIZED VIEW finder_view;
            """
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW finder_view AS
            SELECT unique_taxon_id AS id,
                   'species'       AS type,
                   scientific_name AS name,
                   scientific_name AS name_es,
                   scientific_name AS name_en,
                   determined
            FROM catalog_species
            UNION ALL
            SELECT unique_taxon_id AS id,
                   'synonymy'      AS type,
                   scientific_name AS name,
                   scientific_name AS name_es,
                   scientific_name AS name_en,
                   FALSE           AS determined
            FROM catalog_synonymy
            UNION ALL
            SELECT unique_taxon_id AS id,
                   'family'        AS type,
                   name            AS name,
                   name            AS name_es,
                   name            AS name_en,
                   FALSE           AS determined
            FROM catalog_family
            UNION ALL
            SELECT unique_taxon_id AS id,
                   'genus'         AS type,
                   name            AS name,
                   name            AS name_es,
                   name            AS name_en,
                   FALSE           AS determined
            FROM catalog_genus
            UNION ALL
            SELECT id,
                   'common_name'   AS type,
                   name,
                   name_es,
                   name_en,
                   FALSE           AS determined
            FROM catalog_commonname
            ORDER BY type, name;
            """
        ),
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX finder_view_id
                ON finder_view (id, type);
            """
        ),
        migrations.RunSQL(
            """
            CREATE INDEX finder_view_trgm_es_id
                ON finder_view USING gin(name_es gin_trgm_ops);
            """
        ),
        migrations.RunSQL(
            """
            CREATE INDEX finder_view_trgm_en_id
                ON finder_view USING gin(name_en gin_trgm_ops);
            """
        ),
    ]
