# Generated by Django 4.2.6 on 2024-07-23 15:50
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models
import django.db.models.deletion
from django.utils.translation import activate

from apps.catalog.models import Genus, Species

genus_content_type = ContentType.objects.get_for_model(Genus)


def populate_parent(apps, schema_editor):
    activate("en")
    for species in Species.objects.all():
        species.parent_taxon_id = species.genus.unique_taxon_id
        species.save(force_update=True)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('catalog', '0016_auto_20240719_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='parent_content_type',
            field=models.ForeignKey(default=genus_content_type.id, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='parent_taxon_id',
            field=models.PositiveIntegerField(default=254),
            preserve_default=False,
        ),
        migrations.RunPython(populate_parent),
    ]
