# Generated by Django 4.2.6 on 2024-07-30 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_species_parent_content_type_species_parent_taxon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='order',
            field=models.ForeignKey(blank=True, help_text='order', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.order', verbose_name='Order'),
        ),
        migrations.RunSQL(
            """
            DROP MATERIALIZED VIEW catalog_view;
            """
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW catalog_view AS
            SELECT species.id,
                   species.id_taxa,
                   species.unique_taxon_id,
                   species.taxon_id,
                   kingdom.id      AS kingdom_id,
                   kingdom.name    AS kingdom,
                   division.id     AS division_id,
                   division.name   AS division,
                   classname.id    AS classname_id,
                   classname.name  AS classname,
                   "order".id      AS order_id,
                   "order".name    AS "order",
                   family.id       AS family_id,
                   family.name     AS family,
                   genus.id        AS genus_id,
                   genus.name      AS genus,
                   species.scientific_name,
                   species.scientific_name_full,
                   species.specific_epithet,
                   species.scientific_name_authorship,
                   species.subspecies,
                   species.ssp_authorship,
                   species.variety,
                   species.variety_authorship,
                   species.form,
                   species.form_authorship,
                   species.in_argentina,
                   species.in_bolivia,
                   species.in_peru,
                   status.name     AS status,
                   status.name_es  AS status_es,
                   status.name_en  AS status_en,
                   species.minimum_height,
                   species.maximum_height,
                   species.notes,
                   species.type_id,
                   species.publication,
                   species.volume,
                   species.pages,
                   species.year,
                   species.determined,
                   species.id_taxa_origin,
                   species.created_at,
                   species.updated_at,
                   "user".username AS created_by
            FROM catalog_species species
                 JOIN auth_user "user" ON species.created_by_id = "user".id
                 JOIN catalog_genus genus ON species.genus_id = genus.id
                 JOIN catalog_family family ON genus.family_id = family.id
                 JOIN catalog_order "order" ON family.order_id = "order".id
                 JOIN catalog_classname classname ON "order".classname_id = classname.id
                 JOIN catalog_division division ON classname.division_id = division.id
                 JOIN catalog_kingdom kingdom ON division.kingdom_id = kingdom.id
                 LEFT JOIN catalog_status status ON species.status_id = status.id;
            """
        ),
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX catalog_view_id_idx
                ON catalog_view (id);
            """
        ),
    ]
