# Generated by Django 4.2.6 on 2024-09-16 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0019_auto_20240910_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadSearchRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('requested_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(max_length=200)),
                ('format', models.IntegerField(choices=[(0, 'csv'), (1, 'xlsx')], default=0)),
                ('request_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='ConservationState',
            new_name='ConservationStatus',
        ),
        migrations.AlterModelOptions(
            name='conservationstatus',
            options={'ordering': ['order'], 'verbose_name': 'State of Conservation', 'verbose_name_plural': 'Conservation Status'},
        ),
        migrations.RemoveField(
            model_name='species',
            name='conservation_state',
        ),
        migrations.AddField(
            model_name='species',
            name='conservation_status',
            field=models.ManyToManyField(blank=True, to='catalog.conservationstatus', verbose_name='State of Conservation'),
        ),
    ]
