# Generated by Django 4.2.6 on 2024-09-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_downloadsearchregistration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadsearchregistration',
            name='format',
            field=models.IntegerField(choices=[(0, 'csv'), (1, 'xlsx'), (2, 'tsv')], default=0),
        ),
    ]
