# Generated by Django 5.1.6 on 2025-08-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_references_remove_species_pages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
            ],
        ),
        migrations.AddField(
            model_name='references',
            name='author',
            field=models.ManyToManyField(to='catalog.author', verbose_name='Author'),
        ),
    ]
