# Generated by Django 5.1.6 on 2025-08-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_author_references_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonname',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='commonname',
            name='name_es',
        ),
        migrations.AddField(
            model_name='commonname',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=5, null=True, verbose_name='Language'),
        ),
        migrations.RunSQL(
            """
            DROP MATERIALIZED VIEW IF EXISTS finder_view;
            """
        ),
    ]
