# Generated by Django 5.1.6 on 2025-08-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_remove_commonname_name_en_remove_commonname_name_es_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW finder_view AS
            SELECT taxon_id,
                   unique_taxon_id AS id,
                   'species'       AS type,
                   scientific_name AS name,
                   determined
            FROM catalog_species
            UNION ALL
            SELECT taxon_id,
                   unique_taxon_id AS id,
                   'synonymy'      AS type,
                   scientific_name AS name,
                   FALSE           AS determined
            FROM catalog_synonymy
            UNION ALL
            SELECT taxon_id,
                   unique_taxon_id AS id,
                   'kingdom'       AS type,
                   name            AS name,
                   FALSE           AS determined
            FROM catalog_kingdom
            UNION ALL
            SELECT taxon_id,
                   unique_taxon_id AS id,
                   'division'      AS type,
                   name            AS name,
                   FALSE           AS determined
            FROM catalog_division
            UNION ALL
            SELECT taxon_id,
                   unique_taxon_id AS id,
                   'class'         AS type,
                   name            AS name,
                   FALSE           AS determined
            FROM catalog_classname
            UNION ALL
            SELECT taxon_id,
                   unique_taxon_id AS id,
                   'order'         AS type,
                   name            AS name,
                   FALSE           AS determined
            FROM catalog_order
            UNION ALL
            SELECT taxon_id,
                   unique_taxon_id AS id,
                   'family'        AS type,
                   name            AS name,
                   FALSE           AS determined
            FROM catalog_family
            UNION ALL
            SELECT taxon_id,
                   unique_taxon_id AS id,
                   'genus'         AS type,
                   name            AS name,
                   FALSE           AS determined
            FROM catalog_genus
            UNION ALL
            SELECT id::varchar     AS taxon_id,
                   id,
                   'common_name'   AS type,
                   name,
                   FALSE           AS determined
            FROM catalog_commonname
            ORDER BY type, name;
            """
        ),
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX finder_view_id
                ON finder_view (id, type);
            """
        ),
        migrations.RunSQL(
            """
            CREATE INDEX finder_view_trgm_id
                ON finder_view USING gin(name gin_trgm_ops);
            """
        )
    ]
