# Generated by Django 5.1.6 on 2026-07-17 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20250813_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name_es',
        ),
        migrations.AddField(
            model_name='species',
            name='basionym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='basionym_of', to='catalog.synonymy', verbose_name='Basionym'),
        ),
    ]
